# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uqtdvmcdq-HjTFj6-KAk6zNZSOX92h9O
"""

from transformers import TrainingArguments
import wandb


def initialize_wandb(project_name):
    wandb.init(project=project_name)


def setup_training_args(output_dir="results", epochs=3, batch_size=8):
    return TrainingArguments(
        output_dir=output_dir,
        evaluation_strategy="steps",
        save_strategy="steps",
        logging_dir=f"{output_dir}/logs",
        logging_steps=100,
        save_steps=500,
        eval_steps=500,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        num_train_epochs=epochs,
        weight_decay=0.01,
        save_total_limit=3,
        report_to="wandb",
        load_best_model_at_end=True
    )