# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RqtoKo2C_PDIVnnIyQnABt_RmC9HbMiq
"""

# Configuration globale du projet
DATASET_PATH = "/content/rakitra.csv"
MODEL_NAME = "gpt2"
PROJECT_NAME = "GPT2-HF"
OUTPUT_DIR = "gpt2_results"
EPOCHS = 3
BATCH_SIZE = 8
BLOCK_SIZE = 128
EVAL_SIZE = 0.1