# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RqtoKo2C_PDIVnnIyQnABt_RmC9HbMiq
"""

from trainer import GPT2TrainerHF
from data_preparation.py import prepare_data
from config import DATASET_PATH, MODEL_NAME, PROJECT_NAME, OUTPUT_DIR, EPOCHS, BATCH_SIZE, BLOCK_SIZE, EVAL_SIZE

if __name__ == "__main__":
    # Initialisation du formateur
    trainer = GPT2TrainerHF(model_name=MODEL_NAME, project_name=PROJECT_NAME)

    # Préparation des données
    tokenized_train, tokenized_eval = prepare_data(DATASET_PATH, trainer.tokenizer, block_size=BLOCK_SIZE, eval_size=EVAL_SIZE)

    # Configuration des arguments d'entraînement
    training_args = trainer.setup_training_args(output_dir=OUTPUT_DIR, epochs=EPOCHS, batch_size=BATCH_SIZE)

    # Entraînement du modèle
    trainer.train(tokenized_train, tokenized_eval, training_args)